### ISSUE TITLE
Embed game map

### ISSUE THREAD

**Issue by yjfyy** [soarqin/D2RMH#36]
i use

position =2
scale =4.0
map_centered =1
walkable_color =0,0,0
![1](https://user-images.githubusercontent.com/3762051/141650750-a0f19def-3683-4adf-9c7a-be608b044cbf.jpg)

If walkable_ Color has boundaries, then effect is perfect

**Comment by soarqin** [comment]
1. textures for boundaries are stored in *.dc6 files inside Casc Storage, I don't wanna read files from Casc Storage due to slow bootstrapping
2. customly calculate boundaries may lead to heavy cpu usage on map switching
so this is not scheduled in recent releases. I will add a TODO list later, and put this function in.

**Comment by yjfyy** [comment]
Just add lines, the effect is OK, no need to read dc6 files

**Comment by soarqin** [comment]
draw lines need to test 4 nearby dots for walkable(or non-walkable) dots(check bounds first then check walkable, totaly 8 checks for each dot), this should lead to heavy cpu load
will write test code to see if this is acceptable

**Comment by soarqin** [comment]
added in latest commit, seems like ok for cpu load
don't forget to use new default walkable_color in D2RMH.ini
